### ISSUE TITLE
Add option to delete uploaded image

### ISSUE THREAD

**Issue by szegi** [st900278/Imgur-Uploader-Firefox#1]
It would be great if you could add option to delete uploaded image
sometimes we need to upload something and delete it after someone receive it

**Comment by st900278** [comment]
Do you mean delete from imgur?

**Comment by szegi** [comment]
> Do you mean delete from imgur?

yes
delete in firefox list is also great
but if we have delete link we can add choice to the user or option:)

**Comment by st900278** [comment]
ok, I will add that function as soon as possible

**Comment by szegi** [comment]
thanks for fast response:)

**Comment by st900278** [comment]
Sorry for being late. The version 1.4.0 supported user to delete the file from imgur. You can delete the image in the manage page.

**Comment by szegi** [comment]
ok great, also option with big thumbnails of history uploaded files is great

**Comment by dimqua** [comment]
@st900278 could you also add an option to delete all uploaded images from the addon's history? At least manually.
I upload dozens images every day and my history gets larger and larger, that's inconvenient.
