### ISSUE TITLE
option to upload image from clipboard

### ISSUE THREAD

**Issue by szegi** [st900278/Imgur-Uploader-Firefox#4]
I have another idea that maybe its worth to consider

option to upload image from clipboard
something like
if i copy part of image from other software
like Paint, Irfan View or Print Screen
i click on Imgur-Uploader icon in firefox and there button similar to add image 
option upload clipboard

its just an idea:)

**Comment by st900278** [comment]
Thank you for your advice. I am not sure if addon's api support it or not. I will check it out.

**Comment by st900278** [comment]
done in version 1.3.2

**Comment by szegi** [comment]
great thanks for adding this:)
