### ISSUE TITLE
auto-copy doesn't work

### ISSUE THREAD

**Issue by dromer** [st900278/Imgur-Uploader-Firefox#6]
.. or maybe I'm non sure when this should happen.
After uploading the image the url is not in my clipboard.

58.0.2 (64-bit) on Linux

**Comment by st900278** [comment]
So you upload local image instead of online image?

Auto-copy should work while the notification appeared.

**Comment by dromer** [comment]
No, sorry. This is with online image 'rehosting'.
I see the url in the list of uploaded images.

When is the 'auto-copy' for the url supposed to happen?

**Comment by st900278** [comment]
If you turn on "Auto-Copy to Clipboard: ", it should happen when you see a notification show "Upload success".

**Comment by dromer** [comment]
Nope, I see the notification (is it possible to turn these off or make them disappear faster by the way?), but nothing is put in the clipboard.

**Comment by dromer** [comment]
Ok my excuse I spoke too soon. Now it does work (I had tried half a dozen times before submitting this issue).

However when it doesn't copy properly is when I try to upload from an image that is base64 in the browser. Like the new 'view image' in google images where they disable direct linking to images and just serve the base64 data to the browser. The upload works fine but the link is not copied to the clipboard.

So in this case I do see the url in the list of the plugin, but this link is not coppied.

**Comment by st900278** [comment]
I will try to reproduce the bug these days. 

The notification issue seems not so severe, but you can start a new issue. I might add option for it in the future.

**Comment by st900278** [comment]
So you mean that the copy function failed if the image is base64. But it will work if it is a normal image?

I can't understand what do you mean "view image"

**Comment by dromer** [comment]
Yes.

Right-mousebutton on an image -> 'View image'

**Comment by st900278** [comment]
Oh I see.
I will try to solve the problem. I should say it would take some time to solve this problem. Since "View image" tab is not a normal webpage, it has some possibility it is impossible to inject javascript to copy the url to the clipboard.
Anyway, you can first upload the image and copy successfully if you don't enter the view image tab.

**Comment by dromer** [comment]
Yes true. In my usecase I was hoping that I could use the plugin to host an image when a direct-link isn't available as in said occurence.

Still, great work :)
