### ISSUE TITLE
Changelog tab always opens

### ISSUE THREAD

**Issue by mrror** [st900278/Imgur-Uploader-Firefox#7]
Hi and thanks for this amazingly useful addon.
Since latest update, at every Firefox start it always autoloads the "What's new" tab (moz-extension://{addon id}/templates/announce/1.5.0.html), doesn't matter if I've already closed it after upgrade.
I couldn't find anything that prevents it in about:config. Help or a fix would be welcome. :)

(Firefox 64x 59.0. 2 on Windows 10)

**Comment by st900278** [comment]
Sorry, I never close my browser, so I didn't notice this bug.
Version 1.5.1 was uploaded and the bug should be fixed.
Thank you for reporting this bug.
