### ISSUE TITLE
Update 1.5.0 notification tab keeps appearing

### ISSUE THREAD

**Issue by AyyItsClarkster** [st900278/Imgur-Uploader-Firefox#8]
I'm talking about the one that says 

"Main Difference
Imgur Account Function was implemented..." and so on. I've seen this tab pop-in about 4 times so far, most recent one was around 10:30 PM CST. I'm not doing anything to trigger it, just regular browsing. Not sure if this is just me. Might be nothing, just reporting it.

**Comment by st900278** [comment]
I think this bug is same as the bug reported in #7. It was fixed in 1.5.1. Please update. Than you for reporting and sorry for the inconvenience.
